<?php
	//Set a token with the hash() function, on a random number generated by rand()
	$token = hash("sha256", rand());
	//Set the session data to this token
    $_SESSION["token"] = $token;
    //While we are at it, let's store where we come from
    $_SESSION["org_referer"] = "http://".$_SERVER["HTTP_HOST"] . $_SERVER["SCRIPT_NAME"];

    //Check if we have an for example id after our page and add it to our org_referer value
    if(!empty($_SERVER["QUERY_STRING"]))
    {
    	$_SESSION["org_referer"] = $_SESSION["org_referer"]. "?" . $_SERVER["QUERY_STRING"];
    }
?>